### ISSUE TITLE
do not ask for sudo privilege

### ISSUE THREAD

**Issue by Kyle-Kyle** [ray-cp/pwn_debug#1]
If this project has any dependencies, you can just ask the user to install it instead of asking for sudo privilege.
It looks suspicious.
I was forced to examine the source code a little bit to make sure it does use the sudo privilege properly.

**Comment by ray-cp** [comment]
I have considered this before, but use an absolute directory to compile glibc will make the user experience better. I simply build libc to dir `/glibc`, so it need sudo privilege. sorry about this, I will fix this problem when I have enough time.

**Comment by ray-cp** [comment]
and also only `build.sh` need sudo privilege which compile glibc with debug symbol. for just installing `pwn_debug` you can install `pwn_debug` via command `python setup.py install --user` which does not need sudo privilege.
