### ISSUE TITLE
fmtstr.py

### ISSUE THREAD

**Issue by nowayreal** [ray-cp/pwn_debug#2]
好像这个脚本对于64位程序产生的payload存在0截断问题，导致后面的格式化字符没办法执行。

**Comment by ray-cp** [comment]
roputils也有这个问题，正是因为它有这个问题，我才写的fmtstr模块，format_hn_complete这个函数没有截断问题，可以使用这个函数来进行利用。

**Comment by ray-cp** [comment]
@nowayreal 没有更多问题的话我就关闭这个issue了。。。
